name: k_closest_points_to_origin
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.1.5

dependencies:
  collection: ^1.18.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
